---

- name: Adding Opencast release yum repo
  yum_repository:
    name: opencast-{{ item }}
    file: opencast
    description: "Opencast el 7 Repository - {{ item }}"
    baseurl: "{{ oc_rpm_repo_base_url }}/release/el/7/{{ item }}"
    username: "{{ repo_username }}"
    password: "{{ repo_password }}"
    gpgkey: "{{ oc_rpm_key_url }}"
    gpgcheck: yes
    enabled: yes
    state: present
  with_items:
    - x86_64
    - noarch
  become: yes

- name: Adding optional Opencast yum repos
  yum_repository:
    name: opencast-{{ item }}
    file: "opencast-{{ rpm_repo_suite }}"
    description: "Opencast el 7 Repository - {{ item }}"
    baseurl: "{{ oc_rpm_repo_base_url }}/{{ rpm_repo_suite }}/el/7/{{ item }}"
    username: "{{ repo_username }}"
    password: "{{ repo_password }}"
    gpgkey: "{{ oc_rpm_key_url }}"
    gpgcheck: yes
    enabled: yes
    state: present
  with_items:
    - x86_64
    - noarch
  when: rpm_repo_suite != "release"
  become: yes

- name: Install epel
  yum:
    name: epel-release
    state: latest
  become: yes


