---

- name: Dropping any existing Opencast database schema
  mysql_db:
    state: absent
    name: "{{ oc_db_schema }}"
  become: yes
  tags:
    - never
    - reset

- name: Copying schema to database server
  copy:
    src: mysql5.sql
    dest: /tmp/mysql5.sql
    force: yes
  tags:
    - always

- name: Importing Opencast database schema
  mysql_db:
    state: import
    name: "{{ oc_db_schema }}"
    target: "/tmp/mysql5.sql"
  become: yes
  tags:
    - always
